model_arch: Baseline
LAI: false
n_cams: 20
n_views: 8
backbone: ibn
torch_seed: 0
epoch_freeze_L1toL3: 0
freeze_triplet_branches: 0
freeze_backbone_warmup: false
branch_layer: 3
validation_period: 10
half_precision: true
parallel: false
gpu: null
mean_losses: false
softmax_loss: torch_ce
label_smoothing: 0.1
metric_loss: fastreidtriplet
metric_loss_trans: fastreidtriplet
hard_mining: true
triplet_norm: false
triplet_margin: 0.1
triplet_margin_trans: 0.1
circle_softmax: false
margin_circle: 0.35
scale_circle: 64
group_norm: false
pretrain_gropnorm: false
gn_init: kaiming
pretrain_ongroups: true
BATCH_SIZE: 48
NUM_INSTANCES: 8
num_workers_train: 8
num_workers_teste: 16
y_length: 256
x_length: 256
n_mean:
- 0.5
- 0.5
- 0.5
n_std:
- 0.5
- 0.5
- 0.5
p_hflip: 0.5
p_rerase: 0.5
dataset: Veri776
n_classes: 576
query_dir: /content/drive/MyDrive/vehicle_reid_itsc2023-main/dataset/VeRi/image_query
teste_dir: /content/drive/MyDrive/vehicle_reid_itsc2023-main/dataset/VeRi/image_test
train_dir: /content/drive/MyDrive/vehicle_reid_itsc2023-main/dataset/VeRi/image_train
query_list_file: /content/drive/MyDrive/vehicle_reid_itsc2023-main/dataset/VeRi/name_query.txt
gallery_list_file: /content/drive/MyDrive/vehicle_reid_itsc2023-main/dataset/VeRi/name_test.txt
train_list_file: /content/drive/MyDrive/vehicle_reid_itsc2023-main/dataset/VeRi/name_train.txt
test_keypoint: /content/drive/MyDrive/vehicle_reid_itsc2023-main/dataset/VeRi/keypoint_orient_test.txt
train_keypoint: /content/drive/MyDrive/vehicle_reid_itsc2023-main/dataset/VeRi/keypoint_orient_train.txt
optimizer: Adam
lr: 0.0001
weight_decay: 0.0005
bias_lr_factor: 1
momentum: 0.9
sched_name: Warm_MultiStep
min_lr: 7.75e-05
num_epochs: 20
milestones:
- 40
- 70
- 100
gamma: 0.1
warmup_factor: 0.0
warmup_iters: 10
warmup_method: linear
alpha_ce: 0.6
beta_tri: 1.0
gamma_ce: 0.4
gamma_t: 0.4
pool: GAP
pool_tripletb: GAP
pool_trans: GAP
linear_num: false
n_groups: 4
